type: yolov8_obb
name: yolov8s_obb-r20240111
provider: Ultralytics
display_name: YOLOv8s_obb (DOTA-v1.0)
model_path: https://github.com/CVHub520/X-AnyLabeling/releases/download/v2.3.0/yolov8s-obb.onnx
iou_threshold: 0.7
conf_threshold: 0.25
classes:
  - plane
  - ship
  - storage tank
  - baseball diamond
  - tennis court
  - basketball court
  - ground track field
  - harbor
  - bridge
  - large vehicle
  - small vehicle
  - helicopter
  - roundabout
  - soccer ball field
  - swimming pool

